# Generated by Django 4.1.7 on 2023-04-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count_buy',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
