# Generated by Django 4.1.7 on 2023-04-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_order_count_buy_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='count_buy',
            field=models.IntegerField(default=1),
        ),
    ]
